//----------------------------------------------------
// The following code was generated by CUP v0.10a
// Wed Jul 24 21:44:00 EDT 1996
//----------------------------------------------------

package Utility;
import Parse.*;

/** Cup generated class containing symbol constants. */
public class symName {
	public static final String symnames[] = new String[100];
	static {
		symName.symnames[sym.FUNCTION] = "FUNCTION";
		symName.symnames[sym.EOF] = "EOF";
		symName.symnames[sym.INT] = "INT";
		symName.symnames[sym.GT] = "GT";
		symName.symnames[sym.DIVIDE] = "DIVIDE";
		symName.symnames[sym.COLON] = "COLON";
		symName.symnames[sym.ELSE] = "ELSE";
		symName.symnames[sym.OR] = "OR";
		symName.symnames[sym.NIL] = "NIL";
		symName.symnames[sym.DO] = "DO";
		symName.symnames[sym.GE] = "GE";
		symName.symnames[sym.error] = "error";
		symName.symnames[sym.LT] = "LT";
		symName.symnames[sym.OF] = "OF";
		symName.symnames[sym.MINUS] = "MINUS";
		symName.symnames[sym.ARRAY] = "ARRAY";
		symName.symnames[sym.TYPE] = "TYPE";
		symName.symnames[sym.FOR] = "FOR";
		symName.symnames[sym.TO] = "TO";
		symName.symnames[sym.TIMES] = "TIMES";
		symName.symnames[sym.COMMA] = "COMMA";
		symName.symnames[sym.LE] = "LE";
		symName.symnames[sym.IN] = "IN";
		symName.symnames[sym.END] = "END";
		symName.symnames[sym.ASSIGN] = "ASSIGN";
		symName.symnames[sym.STRING] = "STRING";
		symName.symnames[sym.DOT] = "DOT";
		symName.symnames[sym.LPAREN] = "LPAREN";
		symName.symnames[sym.RPAREN] = "RPAREN";
		symName.symnames[sym.IF] = "IF";
		symName.symnames[sym.SEMICOLON] = "SEMICOLON";
		symName.symnames[sym.ID] = "ID";
		symName.symnames[sym.WHILE] = "WHILE";
		symName.symnames[sym.LBRACK] = "LBRACK";
		symName.symnames[sym.RBRACK] = "RBRACK";
		symName.symnames[sym.NEQ] = "NEQ";
		symName.symnames[sym.VAR] = "VAR";
		symName.symnames[sym.BREAK] = "BREAK";
		symName.symnames[sym.AND] = "AND";
		symName.symnames[sym.PLUS] = "PLUS";
		symName.symnames[sym.LBRACE] = "LBRACE";
		symName.symnames[sym.RBRACE] = "RBRACE";
		symName.symnames[sym.LET] = "LET";
		symName.symnames[sym.THEN] = "THEN";
		symName.symnames[sym.EQ] = "EQ";
	}
};
